targets:
    $default:
        builders:
            swagger_dart_code_generator:
                options:
                    input_folder: 'lib/swaggers/'
                    output_folder: 'lib/swaggers/'
                    input_urls: ['http://192.168.1.101:8080/swagger/v1/swagger.json']