name: nfc_petro
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  camera: ^0.10.5+9
  crypto: ^3.0.3
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_local_notifications: ^17.2.3
  flutter_svg: ^2.0.10+1
  gap: ^3.0.1
  get: ^4.6.6
  get_it: ^7.7.0
  http: ^1.2.2
  intl: ^0.19.0
  keyboard_detection: ^0.7.3
  nfc_manager: ^3.4.0
  path_provider: ^2.1.4
  shamsi_date: ^1.0.4
  shared_preferences: ^2.3.3
  sqflite: ^2.3.3+1
  syncfusion_flutter_charts: ^26.1.42

dev_dependencies:
  flutter_launcher_icons: "^0.13.1"

  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/image/png/app_logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "path/to/image.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "path/to/image.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "path/to/image.png"

flutter:
  uses-material-design: true

  assets:
    - assets/image/png/
    - assets/image/svg/
    - assets/db/
